name: Deploy Audiowalk Infrastructure

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish Identity Management
    uses: ./.github/workflows/publish-identity-management.yml

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Tell the watchtower server there is a new image
        env:
          WATCHTOWER_URL: ${{ vars.WATCHTOWER_URL }}
          WATCHTOWER_TOKEN: ${{ secrets.WATCHTOWER_TOKEN }}
        run: 'curl -I -H "Authorization: Bearer $WATCHTOWER_TOKEN" $WATCHTOWER_URL'
